Project answers_service {
  database_type: 'PostgreSQL'
  Note: 'Answers, points, referrals, and user keys for Votes.'
}

Table points_this_period {
    user_id bigint [unique, not null, ref: > users.user_id]
    points integer [not null, default: 0]
    Note: "Points since the last raffle. Used to assign a user's probability of winning the next raffle."

    indexes {
        points
    }
}

Table total_points {
    user_id bigint [unique, not null, ref: > users.user_id]
    points integer [not null, default: 0]

    indexes {
        points
    }
}

Table referrals {
    from_id bigint [not null, ref: > users.user_id]
    to_id bigint [not null, ref: > users.user_id]
    day integer [not null, note: 'The day (since question 0) that the referral was used.']
    Note: '''
        If the referred user is already verified, the referrer gains points. If the referred user becomes verified
        later, any referral link they used to answer a question will retroactively earn points for the referrer.
    '''

    indexes {
        (from_id, to_id, day) [pk]
        to_id
    }
}

Table answers {
    user_id bigint [not null, ref: > users.user_id]
    day integer [not null, note: 'The day of the question. The first question is day 0.']
    option smallint [not null, note: 'The option number of the answer.']

    indexes {
        (user_id, day) [pk]
        user_id
        (day, option)
    }
}

Table users {
    user_id bigserial [pk, increment]
    verified boolean [not null, default: false, note: 'Has this user been verified as unique by BrightID?']
}

Table keys {
    key_id char(43) [pk, note: '''
        A public key thumbprint anonymously connecting the user to a device or agent. Also used as a "contextId" in
        BrightID. The keypair from which it originates is used for authenticating with the answers service.
        ''']
    user_id bigint [not null, ref: > users.user_id]
    Note: 'Keys used to authenticate users with the answers service.'
}
